config/routes.rb
Rails.application.routes.draw do
  root 'staticpages#home'
  get  '/about', to: 'staticpages#about'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users,          only: [:show]
  resources :posts,          only: [:new, :index, :show, :create, :destroy] do
    resources :comments,     only: [:create, :destroy]
  end
  resources :notifications, only: :index
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :notifications, dependent: :destroy
  validates :content, presence: true, length: { maximum: 300 }
  validates :user_id, presence: true
  validates :post_id, presence: true
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :post
  belongs_to :comment
  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id'
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 300 }
  validates :brand, presence: true
  validates :category, presence: true
  validates :rate, presence: true
  validates :sex, presence: true
  validates :product_name, presence: true
  validate  :picture_size

  def create_notification_comment!(current_user, comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = Comment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      post_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end

  private

  def picture_size
    if picture.size > 5.megabytes
      　 errors.add(:picture, "を5MBバイトより小さいサイズにしてください")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence: true, length: { maximum: 50 }, uniqueness: true
  validates :sex, presence: true
  validates :height, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include AjaxErrorRenderer
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username, :sex, :height])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :sex, :height])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :sex, :height])
  end

  def after_sign_in_path_for(resource)
    posts_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :current_user
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      @post.create_notification_comment!(current_user, @comment.id)
      render :index
    else
      render_ajax_error model: @comment
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      render :index
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id, :user_id)
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications = current_user.passive_notifications.page(params[:page]).per(20)
    @notifications.where(checked: false).includes([:post]).each do |notification|
      notification.update_attributes(checked: true)
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :show, :create, :destroy]
  before_action :current_user, only: :destroy

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result.includes(:user).page(params[:page]).per(5)
  end

  def new
    @post = current_user.posts.build if user_signed_in?
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "投稿が完了しました。"
      redirect_to posts_path
    else
      render 'posts/new'
    end
  end

  def show
    @post = Post.find_by(id: params[:id])
    @comment = Comment.new
    @comments = @post.comments
  end

  def destroy
    Post.find(params[:id]).destroy
    flash[:success] = "投稿を削除しました。"
    redirect_back(fallback_location: root_path)
  end

  private

  def post_params
    params.require(:post).permit(:content, :brand, :category, :rate, :sex, :picture, :product_name)
  end
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def home
    if signed_in?
      redirect_to posts_path
    end
  end

  def about
    if signed_in?
      redirect_to posts_path
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    posts_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def after_update_path_for(resource)
    sign_in_after_change_password? ? posts_path : new_session_path(resource_name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).per(5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "Choosing Clohtes For You"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

  def active_page(path_name)
    if current_page?(path_name)
      "active"
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def unchecked_notifications
    current_user.passive_notifications.where(checked: false)
  end
end

app/views/comments/_form.html.erb
<%= form_with(model: [post, comment]) do |form| %> 
  <div id="error">
    <%# Error Messages display here! %>
  </div>
  <%= render 'shared/error_messages', object: form.object %>
  <div>
    <%= form.text_area :content, placeholder:"コメントを記入する" , id: "comment-textarea"%>
  </div>
  <div class="actions">
    <%= form.submit "コメントをする" %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<%  if comments.present? %> 
  <% comments.each do |comment| %>
    <div class = "comment">
      <% unless comment.id.nil? %>
        <p><%= link_to "#{comment.user.username}さん", user_path(comment.user.id) %></p>
        <p>コメント：<%= comment.content %></p>
        <% if comment.user == current_user %>
          <p><%= link_to 'コメントを削除する',post_comment_path(comment.post_id, comment.id), method: :delete, remote: true %></p>
        <% end %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'index', { comments: @comment.post.comments }) %>")
$('#error_explanation').remove();
$("textarea").val('')

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="mastfoot">
  <div class="inner">
    <p>Choosing Clothes For You</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="masthead">
  <div class="inner">
    <h3 class="masthead-brand">Choosing Clothes For You</h3>
    <ul class="nav nav-masthead justify-content-center">
      <li class="nav-link <%= 'active' if current_page?(posts_path) %>">
        <%= link_to  posts_path do %>
          <i class="fa fa-search", aria-hidden="true" style="font-size: 1.5em;"></i>
          <br><span>SEARCH</span>
        <% end %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-link <%= active_page(notifications_path) %>">
          <%= link_to notifications_path do %>
            <% if unchecked_notifications.any? %>
              <div class "fontawesome">
                <i class="far fa-bell n-bell" aria-hidden="true" style="font-size: 1.5em;"></i> 
                <i class="fa fa-circle n-circle" aria-hidden="true"></i>
              </div>
              <span>NOTICE</span>
            <% else %>
              <i class="far fa-bell" aria-hidden="true"  style="font-size: 1.5em;"></i> 
              <br><span>NOTICE</span>
            <% end %>
          <% end %>
        </li>
        <li class="nav-link <%= active_page(user_path(current_user.id)) %>">
          <%= link_to  user_path(current_user.id) do %>
            <i class="fa fa-user-circle" aria-hidden="true" style="font-size: 1.5em;"></i>
            <br><span>MYPAGE</span>
          <% end %>
        </li>
        <li class="nav-link <%= active_page(new_post_path) %>">
          <%= link_to new_post_path do %>
            <i class="fa fa-edit" aria-hidden="true" style="font-size: 1.5em;"></i>
            <br><span>NEW POST</span>
            <% end %>
          </li>
        <li class="nav-link">
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out-alt" aria-hidden="true" style="font-size: 1.5em;"></i>
            <br><span>LOG OUT</span>
          <% end %>
        </li>
      <% else %>
        <li class="nav-link <%= active_page(root_path) %>">
          <%= link_to root_path do %>
            <i class="fa fa-home" aria-hidden="true" style="font-size: 1.5em;"></i>
            <br><span>HOME</span>
          <% end %>
        </li>
        <li class="nav-link <%= active_page(about_path) %>">
          <%= link_to about_path do %>
            <i class="fa fa-users" aria-hidden="true" style="font-size: 1.5em;"></i>
            <br><span>ABOUT US</span>
          <% end %>
        </li>
        <li class="nav-link <%= active_page(new_user_session_path) %>">
          <%= link_to new_user_session_path do %>
            <i class="fa fa-sign-in-alt" aria-hidden="true" style="font-size: 1.5em;"></i>
            <br><span>LOG IN</span>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_shim_picture.html.erb
<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('最大5MBのファイルまで選択できます. それより小さいファイルを選択してください');
    }
  });
</script>

app/views/layouts/_shim_star_form.html.erb
<script>
  $('#star').raty({
    size     : 36,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    scoreName: 'post[rate]',
    half: true,
  });
</script> 

app/views/layouts/_shim_star_index.html.erb
<script>
$('#star-rate-<%= post.id %>').raty({
  size: 36,
  starOff:  '<%= asset_path('star-off.png') %>',
  starOn : '<%= asset_path('star-on.png') %>',
  starHalf: '<%= asset_path('star-half.png') %>',
  half: true,
  readOnly: true,
  score: <%= post.rate %>,
});
</script>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <div class="cover-container d-flex w-100 h-100 mx-auto flex-column">
      <%= render 'layouts/header' %>
      <div class="text-center">
        <%= render 'layouts/flash_messages' unless current_page?(root_path) %>
        <%= yield %>
      </div>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/notifications/_notification.html.erb
<% visitor = notification.visitor %>
<% visited = notification.visited %>
<div class="notification">
  <span>
    <%= link_to user_path(visitor.id) do %>
      <strong><%= visitor.username %></strong>
    <% end %>
    <%= 'さんが' %>
    <% if notification.post.user_id == visited.id %>
      <%= link_to "あなたの投稿", notification.post, style: "font-weight: bold;" %>
    <% else %>
      <span>
        <%= link_to post_path(notification.post_id) do %>
          <strong><%= notification.post.user.username + 'さんの投稿' %></strong>
        <% end %>
      </span>
    <% end %>
    <%= "にコメントしました" %>
    <p>
      コメント: <%= Comment.find_by(id: notification.comment_id)&.content %>
    </p>
  </span>
  <div class ="notifications_time">
    <small>
      <%= time_ago_in_words(notification.created_at).upcase %>前
    </small>
  </div>
</div>

app/views/notifications/index.html.erb
<% provide(:title, 'Notifications') %>
<!--/ 自分の投稿に対するコメントは通知に表示しない-->
<% notifications = @notifications.where.not(visitor_id: current_user.id).includes([:visitor, :visited, :post]) %>
<% if notifications.exists? %>
  <%= render notifications %>
<% else %>
  <p>通知はありません</p>
<% end %>

app/views/posts/_post.html.erb
  <div class = "post_feed">
    <li id="post-<%= post.id %>" data-post-id="<%= post.id %>">
    <span class="img">
      <%if post.picture? %>
        商品画像 : <%= image_tag post.picture.url, width: '70px'%>
      <% end %>
    </span>
    <span >
      投稿者情報 : <%= link_to post.user do %>
        <%= post.user.username %> <%= post.user.sex %> <%= post.user.height %>
      <% end %>
    </span><br>
    <span>
      <div id="star-rate-<%= post.id %>">評価 : </div>
      <%= render 'layouts/shim_star_index', post: post %>
    </span>
    <span>
      カテゴリー : <%= post.sex %> <%= post.brand %> <%= post.category %><br>
      商品名 : <%= post.product_name %>
    </span><br>
     <span class="content">
      評価内容 : <%= post.content %>
    </span><br>
    <span>
      投稿時間 : <%= post.created_at.strftime("%Y-%m-%d%H:%M") %>
    </span><br>
    <% if post.user == current_user %>
      <%= link_to "投稿削除" , post, data: { confirm: "本当に削除してよろしいでしょうか?" }, method: :delete %>
    <% end %>
    <% unless current_page?(post_path(post.id)) %>
      <%= link_to "コメント", post_path(post.id) %>
    <% end %>
    </li>
  </div>

app/views/posts/index.html.erb
<% provide(:title, 'Post Index') %>
<h1>検索</h1>
<%= search_form_for @q do |f| %>
  <div class="form-group">
    <%= f.label :sex_eq, '性別', class:'col-md-3 col-form-label' %>  
    <%= f.select :sex_eq, ['Womens', 'Mens'] ,{include_blank: '指定なし' } %>
  </div>
  <div class="form-group">
    <%= f.label :brand_eq, 'ブランド', class:'col-md-3 col-form-label' %>  
    <%= f.select :brand_eq, ['UNIQLO', 'GU'] ,{include_blank: '指定なし' } %>
  </div>
  <div class="form-group">
    <%= f.label :category_eq, 'カテゴリー', class:'col-md-3 col-form-label' %>  
    <%= f.select :category_eq, ['アウター', 'トップス', 'ボトムス', 'アクセサリー','シューズ'] ,{include_blank: '指定なし' } %>
  </div>
  <%= f.submit value: "検索" %>    
<% end %>
<ul>
  <%= paginate @posts %>
    <% @posts.each do |post| %>
      <%= render post %>
    <% end %>
  <%= paginate @posts %>
</ul>

app/views/posts/new.html.erb
<% provide(:title, 'Post New') %>
<div class="post_form">
  <%= render 'shared/post_form'%>
</div> 

app/views/posts/show.html.erb
<% provide(:title, 'Post Show') %>
<%= render 'post', post: @post %>
<h4>コメント</h4>
<div id="comments_area">
  <%= render partial: 'comments/index', locals: { comments: @comments } %>
</div>  
<%= render partial: 'comments/form', locals: { comment: @comment, post: @post } %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h3>
      <%= I18n.t("errors.messages.not_saved",
                 count: object.errors.count,
                 resource: object.class.model_name.human.downcase)
       %>
    </h3>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_post_form.html.erb
<%= form_for(@post) do |f| %>
  <h3> レビュー投稿ページ</h3>
  <p>レビューを行う洋服に関しての情報を入力してください</p>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="form-group">
  　<%= f.label :sex, class:'col-md-3 col-form-label' %>
    <%= f.select :sex, [["Mens", "Mens"], ["Womens", "Womens"]],:prompt => "選択してください", class: "form-control" %>
  </div>
  <div class="form-group">
  　<%= f.label :brand, class:'col-md-3 col-form-label' %>
    <%= f.select :brand, [["UNIQLO", "UNIQLO"], ["GU", "GU"]],:prompt => "選択してください", class: "form-control" %>
  </div>
  <div class="form-group">
  　<%= f.label :category, class:'col-md-3 col-form-label' %>
    <%= f.select :category, [["アウター", "アウター"], ["トップス", "トップス"],
    ["ボトムス", "ボトムス"], ["アクセサリー", "アクセサリー"], ["シューズ", "シューズ"]],:prompt => "選択してください", class: "form-control" %>
  </div>
  <div class="form-group">
  　<%= f.label :product_name, class:'col-md-3 col-form-label post_product_name' %>
    <%= f.text_field :product_name, class: "product_name" %>
  </div>
  <div class="form-group" id="star">
    <%= f.label :rate, class:'col-md-3 col-form-label' %>
    <%= f.hidden_field :rate, id: :post_star %>
  </div>
  <%= render 'layouts/shim_star_form' %>  
  <div class="form-group">
     <%= f.label :content, class:'col-md-3 col-form-label' %><br>
     <%= f.text_area :content, class: "content", rows: "8", placeholder:'レビューを記入してみましょう' %>
  </div>
  <span>(商品の画像は任意でアップロードが可能です)</span><br><br>
  <div class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg, image/png' %>
  </div>
  <%= render 'layouts/shim_picture' %>
  <br>
  <div class="form-group justify-content-end">
    <%= f.submit '投稿する', class:"btn btn-success" %>
  </div>
<% end %>

app/views/shared/_status.html.erb
<div class="stats">
  <% if @user.posts.any? %>
    <a  class="no_link">
      <strong class="stat">
       投稿数:<%= @user.posts.count %>
      </strong>
    </a>
  <% else %>
    投稿はまだありません
  <% end %>
</div>

app/views/staticpages/about.html.erb
<% provide(:title, "About") %>
<div class="inner cover">
  <div class="cover-content">
    <h1 class="cover-head">Choosing Clothes For You</h1>
    <p class="lead">
      こちらのサイトは誰でも気軽に洋服についての意見を書いていただける<br>
      サイトになっております。
    </p>
    <p class="lead">
      見るだけでも洋服を買う際の参考にもなりますし、洋服の生産者様も<br>
      皆様からの意見を得て、今後より良い商品を制作する参考にもなります。
    </p>
    <p class="lead">
      どうかご気軽にサービスをご利用ください。<br>
      また、操作がしづらいと感じた方は運営の方まで連絡いただけると幸いです.
    </p>
    <p class="lead">Choosing Clothes For You 運営より</p>
  </div>
</div>

app/views/staticpages/home.html.erb
<% provide(:title, "Home") %>

<div class="inner cover">
  <%= render 'layouts/flash_messages' %>
  <div class="cover-content">
    <h1 class="cover-heading">貴方にとってより良い服選びのために</h1>
    <p class="lead">UNIQLOとGUの商品のレビューサイトです。</p>
    <p class="lead">ログイン画面にサンプルユーザーの情報を記載していますので、そちらからでもログインは可能です。</p>
    <p class="lead">
      <div class="btn btn-lg btn-secondary">
        <%= link_to "Sign Up",  new_user_registration_path %>
      </div>
    </p>
  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h3>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h3>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name) %><br />
<% end %>
<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "アカウント登録", new_registration_path(resource_name) %><br />
<% end %>
<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワードを忘れた方はこちらへ", new_password_path(resource_name) %><br />
<% end %>

app/views/users/show.html.erb
<% provide(:title, "User") %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h3>投稿者情報<br>
        <%= @user.username %><br>
        <%= @user.sex %>
        <%= @user.height %>
      </h3>
      <% if @user == current_user %>
        <%= link_to "プロフィール編集",  edit_user_registration_path %>
      <% end %>
    </section>
    <section class="stats">
      <%= render 'shared/status' %>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @user.posts.any? %>
      <div class ="user_posts">
        <h3>(<%= @user.posts.count %>)</h3>
        <div class ="show_page_paginate">
          <%= paginate @posts %>
        </div>
        <ul class ="user_post">
          <%= render @posts %>
        </ul>
        <div class ="show_page_paginate">
          <%= paginate @posts %>
        </div>
      </div>
    <% end %>
  </div>
</div>